version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Node.jsバージョン
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*' # distフォルダ内のすべてのファイル
  base-directory: dist # Astroのビルド出力ディレクトリ
