name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"
      - run: echo "GITHUB_ENV_SAMPLE=hello" >> "${GITHUB_ENV}"
      - run: echo "${GITHUB_ENV_SAMPLE}"
