name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      SAMPLE_PASSWORD: ${{ secrets.SAMPLE_PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${SAMPLE_PASSWORD}"
      - run: echo "${SAMPLE_PASSWORD:0:1} ${SAMPLE_PASSWORD#?}" # secret はログ出力してはいけない！
